inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  # - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/cache_schema.rb
    - db/queue_schema.rb
    - bin/*
    - vendor/

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

# Rails/SkipsModelValidations:
#   Exclude:
#     - db/migrate/*.active_storage.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
