inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
