default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: foundational_development

test:
  <<: *default
  host: localhost
  database: foundational_test

production:
  <<: *default
  database: foundational_production
  username: foundational
  password: <%= ENV['FOUNDATIONAL_DATABASE_PASSWORD'] %>
